version: "3.9"
services:
  media-share-db:
    image: mysql
    container_name: media-share-db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: media_share_db
      MYSQL_USER: krazezt
      MYSQL_PASSWORD: password
volumes:
  db_data:
